From 1d7823d86d66da027e6d9f9703a04426b1f98ad4 Mon Sep 17 00:00:00 2001
From: Samuel Cabrero <scabrero@zentyal.com>
Date: Wed, 20 Nov 2013 13:21:27 +0100
Subject: [PATCH 3/3] s4:libcli/raw:pysmb: Raise exception on failed
 case_sensitive call

Signed-off-by: Samuel Cabrero <scabrero@zentyal.com>
---
 source4/libcli/pysmb.c | 7 ++-----
 1 file changed, 2 insertions(+), 5 deletions(-)

diff --git a/source4/libcli/pysmb.c b/source4/libcli/pysmb.c
index a24dbd8..608f7cd 100644
--- a/source4/libcli/pysmb.c
+++ b/source4/libcli/pysmb.c
@@ -545,12 +545,9 @@ static PyObject *py_smb_case_sensitive(pytalloc_Object *self, PyObject *args)
 
 	spdata = self->ptr;
 	status = smbcli_set_case_sensitive(spdata->tree, sensitive);
+	PyErr_NTSTATUS_IS_ERR_RAISE(status);
 
-	if (NT_STATUS_IS_OK(status)) {
-		Py_RETURN_TRUE;
-	}
-
-	Py_RETURN_FALSE;
+	Py_RETURN_NONE;
 }
 
 static PyMethodDef py_smb_methods[] = {
-- 
1.8.3.2

